{"uuid":"2930ed78-01e5-4d92-b415-5afd983c0519","historyId":"a14440f79242265c30db2b15e7e31d18","status":"failed","statusDetails":{"message":"expected 1 to deeply equal 2","trace":"AssertionError: expected 1 to deeply equal 2\n    at Context.eval (http://localhost:58092/__cypress/tests?p=cypress\\integration\\Fail\\login1.spec.js:102:18)"},"stage":"finished","steps":[],"attachments":[{"name":"Fail/login1.spec.js:2022-08-05T12:40:58.967Z","type":"image/png","source":"8fa04836-3df6-4d2b-88ac-444c35413cb0-attachment.png"},{"name":"video recording","type":"video/mp4","source":"4b3de9a6-82db-4877-a73b-1467ab462bfd-attachment.mp4"}],"parameters":[],"labels":[{"name":"suite","value":"verify the login for fail"}],"links":[],"start":1659703258694,"name":"verify with valid credential with fail","fullName":"verify with valid credential with fail","stop":1659703259409}